In [7]:
my_function= lambda a,b,c:a+b+c
my_function(1,2,4)


7

In [12]:
mylist=[number for number in range(0,10) if number%2==0]
mylist

[0, 2, 4, 6, 8]

In [14]:
lowercase = 'abcdefghijklmnopqrstuvwxyz'
digits = '0123456789'

correct_answer = [a+b+c+d for a in lowercase for b in lowercase for c in digits for d in digits]

correct_answer[:5] # Display first 50 ids

['aa00', 'aa01', 'aa02', 'aa03', 'aa04']

In [16]:
import numpy as np
mylist=[1,2,3]
x=np.array(mylist)
x

array([1, 2, 3])

In [18]:
x=np.array([2,4,5])
x

array([2, 4, 5])

In [22]:
x=np.array([[1,2,3],[1,4,5]])
x.shape

(2, 3)

In [24]:
n=np.arange(0,20,2)
n

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [26]:
n=n.reshape(2,5)
n

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [31]:
n=np.linspace(0,10,30)
n

array([ 0.        ,  0.34482759,  0.68965517,  1.03448276,  1.37931034,
        1.72413793,  2.06896552,  2.4137931 ,  2.75862069,  3.10344828,
        3.44827586,  3.79310345,  4.13793103,  4.48275862,  4.82758621,
        5.17241379,  5.51724138,  5.86206897,  6.20689655,  6.55172414,
        6.89655172,  7.24137931,  7.5862069 ,  7.93103448,  8.27586207,
        8.62068966,  8.96551724,  9.31034483,  9.65517241, 10.        ])

In [34]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [35]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [36]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [39]:
x=[1,3,6]
np.diag(x)

array([[1, 0, 0],
       [0, 3, 0],
       [0, 0, 6]])

In [40]:
np.array([1,2,3]*3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [41]:
np.repeat([1,2,3],4)

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3])

In [7]:
import numpy as np

In [10]:
p=np.ones([2,3],float)


In [11]:
np.vstack([p,3*p])

array([[1., 1., 1.],
       [1., 1., 1.],
       [3., 3., 3.],
       [3., 3., 3.]])

In [12]:
np.hstack([4*p,p])

array([[4., 4., 4., 1., 1., 1.],
       [4., 4., 4., 1., 1., 1.]])

In [13]:
#OPERATIONS


In [19]:
x=[1,2,3]
x=np.array(x)
y=[2,2,2]
y=np.array(y)


In [20]:
x+y

array([3, 4, 5])

In [21]:
x**2

array([1, 4, 9], dtype=int32)

In [22]:
x*y

array([2, 4, 6])

In [24]:
x.dot(y)

12

In [28]:
z=np.array([x,x**3])
z

array([[ 1,  2,  3],
       [ 1,  8, 27]])

In [29]:
print(z.shape )

(2, 3)


In [30]:
z.T

array([[ 1,  1],
       [ 2,  8],
       [ 3, 27]])

In [31]:
z.T.shape

(3, 2)

In [32]:
z.dtype

dtype('int32')

In [33]:
z.astype('f')

array([[ 1.,  2.,  3.],
       [ 1.,  8., 27.]], dtype=float32)

In [34]:
a=np.array([1,2,3,-4,-6,10])

In [35]:
a.sum()

6

In [36]:
a.max()

10

In [37]:
a.min()

-6

In [38]:
a.mean()

1.0

In [39]:
a.std()

5.163977794943222

In [40]:
#index of max and min value
a.argmax()

5

In [41]:
a.argmin()

4

In [42]:
#INDEXING/SLICING

In [43]:
np.arange(13)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [45]:
s=np.arange(13)**2
s

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144],
      dtype=int32)

In [46]:
s[0],s[3],s[7:10]

(0, 9, array([49, 64, 81], dtype=int32))

In [47]:
s[1:5]

array([ 1,  4,  9, 16], dtype=int32)

In [48]:
s[-4:]

array([ 81, 100, 121, 144], dtype=int32)

In [17]:
n=np.arange(36)
n.resize((6,6))
n

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [18]:
n[:,2:4]

array([[ 2,  3],
       [ 8,  9],
       [14, 15],
       [20, 21],
       [26, 27],
       [32, 33]])

In [19]:
n[n>27]

array([28, 29, 30, 31, 32, 33, 34, 35])

In [20]:
n[n>29]=31
n

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [31, 31, 31, 31, 31, 31]])

In [21]:
n_copy=n.copy()
n_copy[:]=2
print(n_copy)
print()
print(n)

[[2 2 2 2 2 2]
 [2 2 2 2 2 2]
 [2 2 2 2 2 2]
 [2 2 2 2 2 2]
 [2 2 2 2 2 2]
 [2 2 2 2 2 2]]

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [31 31 31 31 31 31]]


In [22]:
old = np.array([[1, 1, 1],
                [1, 1, 1]])

new = old
new[0, :2] = 0

print(old)


[[0 0 1]
 [1 1 1]]


In [23]:
#ITERATING OVER ARRAYS

In [25]:
test=np.random.randint(0,20, (4,3))
test

array([[19, 11,  4],
       [ 6,  2,  2],
       [18, 11, 17],
       [ 0,  1, 11]])

In [28]:
for row in test:
    print(row)

[19 11  4]
[6 2 2]
[18 11 17]
[ 0  1 11]


In [30]:
for i in range(len(test)):
    print(test[i])

[19 11  4]
[6 2 2]
[18 11 17]
[ 0  1 11]


In [31]:
for i ,row in enumerate(test):
    print('row',i,'is',row)

row 0 is [19 11  4]
row 1 is [6 2 2]
row 2 is [18 11 17]
row 3 is [ 0  1 11]


In [33]:
test2=test**2
test2

array([[361, 121,  16],
       [ 36,   4,   4],
       [324, 121, 289],
       [  0,   1, 121]], dtype=int32)

In [38]:
for i,j in zip(test,test2):
    print(i,'+',j ,'=',i+j)

[19 11  4] + [361 121  16] = [380 132  20]
[6 2 2] + [36  4  4] = [42  6  6]
[18 11 17] + [324 121 289] = [342 132 306]
[ 0  1 11] + [  0   1 121] = [  0   2 132]
